### PR TITLE
Remove trackers embedded in URLs

### PR DESCRIPTION
**Pull request by Boruch-Baum**
w3m--url-strip-queries and its associated defcustom
w3m-strip-queries-alist allow users to remove from URLs bogus queries
that don't query anything but instead send to the network tracking
data about the user's and/or behavior.

The default is pre-configured with a rather tame but common example
that tells websites that the user is arriving there from a newsfeed
instead of directly or via a search engine.

Honestly, I thought this had already been implemented somewhere, but I
couldn't find it, and it was easy to write...

### CODE REVIEW

**Comment by Boruch-Baum** [comment]
With the default settings, the feature can be tested by having an rss reader use emacs-w3m to open a article on slashdot.

**Comment by emacs-w3m-notifier** [comment]
This is very useful functionality. Thank you for working on it.

Vladimir

**Comment by Boruch-Baum** [comment]
You're quite welcome, Vladimir.

Here are some of my notes for possible future related work. If you (or
anyone else reading this) know how to un-obfuscate or de-shorten URLs,
please let me know.

+ Modify the cdr spec of the data structure's elements to allow for a
  function instead of or in addition to a regex string. This would
  allow for features such as logging or replacing occurrences of a
  query, instead of just deleting a query.

  + General purpose logging could be used to collect tracker queries
    to be acted upon in the future.

+ Address other forms of embedded trackers:

  + Obfuscated trackers encoded (eg. base64) in the url final segment
    along with any fragments and queries.

    + eg. some stackexchange mailing list links

  + URL shortening services are a known tracking vector.
    eg. https://threatpost.com/fishwrap-social-media-old-news/145641/

+ Collect more common tracker queries for use in the default data
  structure.

  + My persoal internet usage has limited exposure, so maybe post to
    the mailing list asking for volunteers to supply additions
    regexes.

(note: this is a test of using magit forge M-x forge-create-post to
respond to a github comment from within emacs)

**Comment by Boruch-Baum** [comment]
Here are two more regexes, this time from an email referrer, with an
explicit ID tokken:

```
(setq w3m-strip-queries-alist
  '(("^https?://.*" "&?utm_source=[^&]+")
    ("^https?://.*" "&?utm_medium=[^&]+")
    ("^https?://.*" "&?utm_campaign=[^&]+")
    ("^https?://.*" "&?email_source=[^&]+")
    ("^https?://.*" "&?email_token=[^&]+")
    ))
```

**Comment by yamaoka** [comment]
Merged to the `modernize201906` branch.  Thanks.

**Comment by yamaoka** [comment]
As having been merged to the git master, closing.

**Pull request closed without merging**
