### PR TITLE
Bb force wide

### PR DESCRIPTION
**Pull request by Boruch-Baum**
This continues PR#98 with work that is discussed in the github comments there: 

+ After rendering a db-history page, advance POINT to a position that is useful for user,the first db-history entry.

+ Add a docstring to function `w3m--goto-url--handler-function`

### CODE REVIEW

**Comment by yamaoka** [comment]
Merged.　Thanks.
Well, in the last reply in PR#98 I really wanted to say was:
```
When launching w3m-db-history with no prefix argument, the point is positioned on the third db entry.
Is it intentional?
```
:-)

**Comment by Boruch-Baum** [comment]
On 2021-07-29 23:26, yamaoka wrote:
>    Merged.　Thanks.
>    Well, in the last reply in PR#98 I really wanted to say was:
> When launching w3m-db-history with no prefix argument, the point is positioned o
> n the third db entry.
> Is it intentional?

No, that sounds like a bug, but I can't reproduce it, even restarting
with a clean emacs.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by yamaoka** [comment]
Hmm, this is my case.　What's wrong?
w3m-db-history

**Comment by Boruch-Baum** [comment]
On 2021-08-01 16:57, yamaoka wrote:
>    Hmm, this is my case.　What's wrong?
>    [1]w3m-db-history

I think the picture cleared things up for me. While earlier you didn't
account for multi-page, now I didn't account for single page. Changing
the (forward-line 6) of my previous commit to (forward-line 3) should
correct this for both cases. Does it on your side?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by yamaoka** [comment]
> Changing the `(forward-line 6)` of my previous commit to `(forward-line 3)` should correct this for both cases.

Yeah, it makes it correct for the both cases.　Pushed.

**Comment by Boruch-Baum** [comment]
On 2021-08-01 18:15, yamaoka wrote:
>      Changing the (forward-line 6) of my previous commit to (forward-line
>      3) should correct this for both cases.
>
>    Yeah, it makes it correct for the both cases.　Pushed.

Sorry about that. I just pushed a commit to github, now PR #100.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Pull request merged**
