### PR TITLE
Fix regex used to detect if there are visible w3m windows.

### PR DESCRIPTION
**Pull request by analyticd**
Used when restoring a w3m session.

### CODE REVIEW

**Comment by yamaoka** [comment]
Well, I guessed this is for the case where there is only a session-select window (and the regexp matches its buffer name, i.e., " *w3m-session select*") but no w3m-mode buffer presents in the selected frame.　Is it right?

**Comment by analyticd** [comment]
The fix covers many cases. In my case, I have w3m set to remember the last session (with multiple tabs) and it so happens that I often have as my first tab 

    *w3m About emacs-w3m (about:)*

and I have in my config a function that I find useful:

```
(defun my-w3m-rename-buffer (url)
    "Suitable for adding to `w3m-display-hook'."
    (rename-buffer (format "*w3m %s (%s)*"
                           (or w3m-current-title "")
                           (or w3m-current-url ""))
                   t))
```

Of course this alters w3m's basic behavior, but there is no harm I think to changing it and that makes the resurrection of sessions with such a function possible without hurting the basic functionality of w3m I think. Thanks for emacs-w3m, it is awesome!

**Comment by yamaoka** [comment]
I see.　Thanks.　I thought it's better to test if the `major-mode` is `w3m-mode` rather than to test the buffer name, so I did so.　Please let me know if my change causes any trouble.
Btw, could you let me know your real full name and email if possible.　I'd like to register your change in the ChangeLog file in a usual way.

**Comment by analyticd** [comment]
I like the way you changed it, it makes more sense to check for the mode. You could just use @analyticd  as name and email as you already have it in the change log, or, you can just leave it out of the changelog, I don't mind.

**Pull request merged**
