### PR TITLE
BUGFIX: don't put about://history/ pages in history.

### PR DESCRIPTION
**Pull request by Boruch-Baum**
This is a one-line addition to the beginning of function w3m-history-push. It prevents the about:history page from accumulating entries of itself. What otherwise happens is that each time someone presses 'h' another copy of the history is added to the history list for the buffer! Press 'h' and 'B' many times and you end up with many copies of the history in your buffer's history, when really it should appear ZERO times.

### CODE REVIEW

**Comment by emacs-w3m-notifier** [comment]
Let me improve on this by adding another commit, because the same thing
happens with about:bookmark. I can't think of any case that an about://...
url should be on the history, so let me widen the test.

On 2021-01-03 03:17, Boruch Baum wrote:
>    This is a one-line addition to the beginning of function
>    w3m-history-push. It prevents the about:history page from accumulating

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
I think all cases are covered now, and it should be ready for merge.

This PR now has the side benefit that now users can restore from "about://source" and "about://heading" by using keybinding 'B' w3m-view-previous-page. I remember my first encounters with those features (bound to '\' and '=' by default) were surprising and I had now idea what key I had pressed and how to return to where I was. Now the 'B' keybinding does what a user expects in the sense of undoing the prior navigation.

BTW. Github is now telling me I can upload videos as part of my comments. What a feature to abuse! Please don't!

**Comment by yamaoka** [comment]
I stopped merging your commits because of a lot of conflicts in ChangeLog (and others?).  I have no time to check and verify them one by one.

**Comment by Boruch-Baum** [comment]
Simple fix to the changelog, of things already merged in other PR's I think. The files themselves look more modified than they really are because of tab/space inconsistency, but you long ago automated a fix for that, no?

**Comment by yamaoka** [comment]
There was still a bit conflict with HEAD/ChangeLog but that's ok.
I've restored `no-store-pos` in `w3m-view-previous-page` (it should have been easily found when performing `make`).

**Comment by Boruch-Baum** [comment]
On 2021-01-03 20:30, yamaoka wrote:
>    There was still a bit conflict with HEAD/ChangeLog but that's ok.
>    I've restored no-store-pos in w3m-view-previous-page (it should have
>    been easily found when performing make).

Oooh, yes, an oversight/bug. Thank you. I'll correct it on my side also.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
On 2021-01-04 01:42, Boruch Baum wrote:
> On 2021-01-03 20:30, yamaoka wrote:
> >    There was still a bit conflict with HEAD/ChangeLog but that's ok.
> >    I've restored no-store-pos in w3m-view-previous-page (it should have
> >    been easily found when performing make).
>
> Oooh, yes, an oversight/bug. Thank you. I'll correct it on my side also.
>
Now I'm confused. I don't see that variable otherwise defined in the
function, or anywhere else.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by yamaoka** [comment]
I meant the optional lexical argument 'no-store-pos' that is passed to the function 'w3m-view-previous-page'. 
The function `w3m--prompt-for-unknown-content-type' sets it.

**Pull request merged**
