### PR TITLE
Replace function w3m-view-this-url-1 with calls to w3m-goto-url{,-new-session}

### PR DESCRIPTION
**Pull request by Boruch-Baum**
Prompted by item 31 of mailing list #13417

### CODE REVIEW

**Comment by yamaoka** [comment]
Merged into the `modernize201906` branch manually.　Thanks.
I'll do it on also some of the other open PRs little by little...

**Comment by Boruch-Baum** [comment]
On 2019-07-02 06:39, yamaoka wrote:
>    Merged into the modernize201906 branch manually.　Thanks.
>    I'll do it on also some of the other open PRs little by little...

Great!

What's happening now with the master branch? That's the branch visible
to melpa, so if you're building many commits on another branch, you
don't seem to want feedback or testing from many people, and its unclear
to me what is the current 'main' branch.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by yamaoka** [comment]
The git master is the main branch naturally, and where to put the modernize201906 branch back to is the master branch of course.　I plan to do it after merging some (not all probably) open PRs and testing.

**Comment by Boruch-Baum** [comment]
On 2019-07-02 14:58, yamaoka wrote:
>    The git master is the main branch naturally, and where to put the
>    modernize201906 branch back to is the master branch of course.　I plan
>    to do it after merging some (not all probably) open PRs and testing.

My second-best input / suggestion is to perform individual merges to
master after each PR or major feature and to stagger them a day or two
apart after testing. That would give people who update via MELPA a
chance to report back any problems that they have and make it easier to
track down a bug's source. You already know by first-best advice - I've
mentioned several times my idea for a MELPA testing branch, so this will
be the last time I advocate for that.

You've taken upon yourself to do a lot of great work with the code clean
up. Thanks.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by yamaoka** [comment]
As having been merged to the git master, closing.

**Pull request closed without merging**
