### PR TITLE
Address error in toggling vertical/horizontal popup window splits.

### PR DESCRIPTION
**Pull request by vjorlikowski**
By the time split-window is called, the locally let selected-window variable is no longer a valid window. Thus, we *actually* need to call the selected-window function here.

### CODE REVIEW

**Comment by Boruch-Baum** [comment]
On 2021-06-09 14:23, vjorlikowski wrote:
>    By the time split-window is called, the locally let selected-window
>    variable is no longer a valid window. Thus, we actually need to call
>    the selected-window function here.

Curious. I have that patch already applied. What I mean is that I'm
seeing line 11246 already 'corrected'.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by vjorlikowski** [comment]
Agreed - but it's not in the master branch.
In any case - preparing to close this merge request, and open a separate one; I realized that w3m-select-buffer-window wasn't properly being updated, either.

**Comment by vjorlikowski** [comment]
Closing, to re-open with additional change.

**Comment by vjorlikowski** [comment]
Sigh; Github had already noticed the second change.
Re-opening...

**Comment by vjorlikowski** [comment]
Apologies for the churn.

**Comment by Boruch-Baum** [comment]
On 2021-06-09 14:54, vjorlikowski wrote:
>    Apologies for the churn.

No need. It gives me consolation that I'm not the only one who has
trouble juggling these things.

1] In that spirit, since I have firefox open, I'll try and
   play with their 'code review' feature to make a minor comment
   regarding line 11250. Let's see if it works and how github sends us
   feedback.

1.1] I have an Emacs package installed called github-review, but for the
     way I have this project (dis-)organized, I'm not sure how to use
     it.

2] Can you easily provide a recipe to reproduce the problem calling for
   this commit. Katsumi-san may not need this, so it might not be
   mandatory in this case, but it would be useful for me.


--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by vjorlikowski** [comment]
In re: (2) - certainly!

When in an emacs-w3m "w3m mode" buffer - I press "C-s", which is bound to "w3m-select-buffer".
This places me in a new window, with a buffer that's using "w3m buffers" mode.

In this buffer, I press "C-c C-s" - which is bound to "w3m-select-buffer-toggle-style"; this is *supposed* to toggle the "w3m buffers" window between vertical and horizontal orientations.

Without the end result of my mishmash of commits? The window containing the "w3m buffers" mode disappears, and I get an error message stating that the window that previously contained it no longer exists.

With the end result of this set of commits? The "w3m buffers" window properly toggles between vertical and horizontal orientations (which happens by deleting the old window, and creating a new one in the new orientation; the use of the "selected-window" variable references the window that had been deleted, while using the "(selected-window)" function instead selects the window that *should* be split as part of the creation of the new window containing the "w3m buffers" buffer).

**Comment by Boruch-Baum** [comment]
On 2021-06-09 18:19, vjorlikowski wrote:
>    In re: (2) - certainly!
>    ..

OK. So where do we stand now after all the back and forth? The lack of
parentheses around "selected-window" is clearly a typo bug, right? And
I'm always happy with better documentation, so I'm in favor of that. Is
this PR now in an acceptable state?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by yamaoka** [comment]
Pushed to master.  Thank you for fixing it.

**Comment by vjorlikowski** [comment]
We're all set, after the back-and-forth, and thank you so much for merging!

Part of the reason for the back-and-forth: I mis-took what was being tracked with w3m-select-buffer-window. It was my error, and I'm somewhat embarrassed of it. :)

**Comment by Boruch-Baum** [comment]
On 2021-06-19 08:33, vjorlikowski wrote:
>    Part of the reason for the back-and-forth: I mis-took what was being
>    tracked with w3m-select-buffer-window. It was my error, and I'm
>    somewhat embarrassed of it. :)

No need to be. For me, it had the side-benefit of giving me an excuse to
evaluate the github 'code-review' feature...

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Pull request merged**
